language: node_js
node_js:
- '8'
before_script: npm install
script:
  npm run test
cache:
  directories:
    -node_modules
deploy:
  provider: heroku
  api_key:
    secure: GoWUciDLSDCO+anndi98Hp+6ntdXez3cJdoDukt3G5eh6dx540tAYmRJ2SlpWBFoJ4XiHbJMlzmNGmzdoPNDLaC7gkHxh8XRxIm/6olSlJMF8NrA15gKocqB6L0ecOJt4mFUs8s9r59vZ2ICFWf169Op/EbUcz4Pf6nabWtGdxqpFKcXqvppWqHcyQfOoWfKuK+acEC7WRBbqSCUkRQJU1x26NHkegdy97Sm++g76IpeWwG1/EUyb8Qd1Xoe+8oEHb/D0tBSvA54kFr1aU0qETIm4sGsViHmWQZ6MTinalYRvQdWpa6gvEQcqb7oqPoDKv1Uab+QlBIsxM4SppxI7YMxXDIoKUI9plKFZ5UhegRssdNiSxnls0FPeZcq93qg7BY60p8Qvix5xkQpa9UvqHMLvKrK3KlNkyhlQQ6UXmE6kHymdGKafC6s7u7sX97pLcQXtfJQoLtaTtb2lzVSASbUwaaP3vUHPU+DwjrcH0xR1Jyb8lGD9IdrhN4xjLMrL5jsraLTqtkR3UbSWDZ6jzfAP9vRBqdw3YPQBM+Mo+B3TS+2iA4RN6a3jvH8V/oiARVLJH8F48Wwvr/mXotXURUND5JJhsHtsM/6c2WppytHUsGj2KQF0ITZUPsFkSPwq10fYIxdDi0nlAAwb9129fiG+vr1AfCzwA9Qj1sjicQ=
  app: prueba-travis-herouku
  on:
    repo: carlamendozadominguez/Prueba-Travis-Heroku
